/**
 * pdf.js — PDF assembly using jsPDF and svg2pdf
 */

const BOOKLET_W = 107.95; // 4.25"
const BOOKLET_H = 139.7;  // 5.5"
const BM = 3;

const LEFT_W   = BOOKLET_W * 0.40;
const RIGHT_X  = LEFT_W;
const RIGHT_W  = BOOKLET_W - LEFT_W;

const GREEN_TOP = BOOKLET_H * 0.60;
const GREEN_H   = BOOKLET_H - GREEN_TOP - BM;
const GREEN_W   = LEFT_W - BM * 2;

const LETTER_W = 215.9;  // 8.5"
const LETTER_H = 279.4;  // 11"

export async function assemblePdf({ holes, courseName, colors }) {
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: [BOOKLET_W, BOOKLET_H] });

  addCoverPage(pdf, courseName, colors, BOOKLET_W, BOOKLET_H);
  const sorted = [...holes].sort((a, b) => a.holeNum - b.holeNum);
  for (const hole of sorted) {
    pdf.addPage([BOOKLET_W, BOOKLET_H], 'portrait');
    await drawHolePage(pdf, hole, colors, 0, 0);
  }
  return pdf.output('blob');
}

export async function assemblePrintPdf({ holes, courseName, colors }) {
  const { jsPDF } = window.jspdf;
  const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'letter' });

  const holeMap = new Map(holes.map(h => [h.holeNum, { type: 'hole', ...h }]));
  const order = [18, 16, null, 1, null, 2, 17, 15, 14, 12, 3, 5, 4, 6, 13, 11, 10, null, 7, 'cover', 8, null, 9, null];
  const pages = order.map(item => item === 'cover' ? { type: 'cover', courseName, colors } : (item === null ? { type: 'blank' } : (holeMap.get(item) || { type: 'blank' })));
  const origins = [[0, 0], [BOOKLET_W, 0], [0, BOOKLET_H], [BOOKLET_W, BOOKLET_H]];

  let isFirstSheet = true;
  for (let i = 0; i < pages.length; i += 4) {
    if (!isFirstSheet) pdf.addPage('letter', 'portrait');
    isFirstSheet = false;
    for (let q = 0; q < 4; q++) {
      const page = pages[i + q], [ox, oy] = origins[q];
      if (page.type === 'cover') addCoverPage(pdf, page.courseName, page.colors, BOOKLET_W, BOOKLET_H, ox, oy);
      else if (page.type === 'hole') await drawHolePage(pdf, page, colors, ox, oy);
    }
    drawCutGuides(pdf);
  }
  return pdf.output('blob');
}

function addCoverPage(pdf, courseName, colors, w, h, ox = 0, oy = 0) {
  pdf.setFillColor(255, 255, 255);
  pdf.rect(ox, oy, w, h, 'F');
  pdf.setTextColor(0, 0, 0);
  const cx = ox + w / 2, cy = oy + h / 2;
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.text(courseName || 'Golf Course', cx, cy - 8, { align: 'center' });
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(10);
  pdf.text('Yardage Book', cx, cy + 4, { align: 'center' });
  pdf.setFontSize(5);
  pdf.text('Generated by OpenYardage', cx, oy + h - 4, { align: 'center' });
}

async function drawHolePage(pdf, hole, colors, ox, oy) {
  // Right Panel: Draw Rough Background then vector SVG
  pdf.setFillColor(...hexToRgb(colors.rough));
  pdf.rect(ox + RIGHT_X, oy, RIGHT_W, BOOKLET_H, 'F');
  const fitHole = fitImage(hole.holeWidth, hole.holeHeight, ox + RIGHT_X, oy, RIGHT_W, BOOKLET_H);
  
  const holeSvgDoc = new DOMParser().parseFromString(hole.holeSvg, 'image/svg+xml').documentElement;
  
  // Explicitly set the coordinate mapping so svg2pdf knows how to scale it down
  holeSvgDoc.setAttribute('viewBox', `0 0 ${hole.holeWidth} ${hole.holeHeight}`);
  holeSvgDoc.setAttribute('width', fitHole.w);
  holeSvgDoc.setAttribute('height', fitHole.h);
  
  await pdf.svg(holeSvgDoc, { 
    x: fitHole.x, 
    y: fitHole.y, 
    width: fitHole.w, 
    height: fitHole.h 
  });

  // Left Panel: White background
  pdf.setFillColor(255, 255, 255);
  pdf.rect(ox, oy, LEFT_W, BOOKLET_H, 'F');
  pdf.setTextColor(0, 0, 0);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(18);
  pdf.text(`Hole  ${hole.holeNum}`, ox + BM, oy + BM + 6);
  
  let textY = oy + BM + 13;
  if (hole.par) {
    pdf.setFont('helvetica', 'normal');
    pdf.setFontSize(11);
    pdf.text(`Par  ${hole.par}`, ox + BM, textY);
    textY += 6;
  }

  // Placeholder lines
  textY += 3;
  pdf.setDrawColor(200, 200, 200);
  pdf.setLineWidth(0.2);
  for (let row = 0; row < 3; row++) {
    const y = textY + row * 5;
    pdf.circle(ox + BM + 2, y, 1.2, 'S'); pdf.line(ox + BM + 5, y, ox + BM + 16, y);
    pdf.circle(ox + BM + 20, y, 1.2, 'S'); pdf.line(ox + BM + 23, y, ox + BM + 34, y);
  }

  // Notes section
  const notesY = textY + 20;
  pdf.setFontSize(7);
  pdf.text('Notes', ox + BM, notesY);
  pdf.setDrawColor(0, 0, 0);
  pdf.setLineWidth(0.3);
  pdf.line(ox + BM, notesY + 1, ox + LEFT_W - BM, notesY + 1);

  // Green Inset vector SVG
  pdf.setFillColor(255, 255, 255);
  pdf.rect(ox + BM, oy + GREEN_TOP, GREEN_W, GREEN_H, 'F');
  const gi = fitImage(hole.greenWidth, hole.greenHeight, ox + BM, oy + GREEN_TOP, GREEN_W, GREEN_H);
  const bottomY = oy + GREEN_TOP + GREEN_H - gi.h;
  
  const greenSvgDoc = new DOMParser().parseFromString(hole.greenSvg, 'image/svg+xml').documentElement;
  
  // Explicitly set the coordinate mapping so svg2pdf knows how to scale it down
  greenSvgDoc.setAttribute('viewBox', `0 0 ${hole.greenWidth} ${hole.greenHeight}`);
  greenSvgDoc.setAttribute('width', gi.w);
  greenSvgDoc.setAttribute('height', gi.h);
  
  await pdf.svg(greenSvgDoc, { 
    x: gi.x, 
    y: bottomY, 
    width: gi.w, 
    height: gi.h 
  });
}

function drawCutGuides(pdf) {
  pdf.setDrawColor(180, 180, 180);
  pdf.setLineWidth(0.15);
  drawDashedLine(pdf, LETTER_W / 2, 0, LETTER_W / 2, LETTER_H, 4, 2);
  drawDashedLine(pdf, 0, LETTER_H / 2, LETTER_W, LETTER_H / 2, 4, 2);
}

function drawDashedLine(pdf, x1, y1, x2, y2, dashLen, gapLen) {
  const dx = x2 - x1, dy = y2 - y1, len = Math.sqrt(dx * dx + dy * dy);
  const ux = dx / len, uy = dy / len;
  let pos = 0;
  while (pos < len) {
    const segEnd = Math.min(pos + dashLen, len);
    pdf.line(x1 + ux * pos, y1 + uy * pos, x1 + ux * segEnd, y1 + uy * segEnd);
    pos = segEnd + gapLen;
  }
}

export function fitImage(imgW, imgH, boxX, boxY, boxW, boxH) {
  const imgAspect = imgW / imgH, boxAspect = boxW / boxH;
  let w, h;
  if (imgAspect > boxAspect) { w = boxW; h = boxW / imgAspect; } 
  else { h = boxH; w = boxH * imgAspect; }
  return { x: boxX + (boxW - w) / 2, y: boxY + (boxH - h) / 2, w, h };
}

export function hexToRgb(hex) {
  const h = hex.replace('#', '');
  return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
}